=== abderrahim1992/STB_PROJECT/src/main/resources/stb.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://univ.fr/stb" xmlns="http://univ.fr/stb">
<xs:element name="stb" type="stbType"/>
<xs:element name="priorite" type="prioriteType"/>
<xs:element name="membre" type="equipeType"/>
<xs:element name="exigence" type="exigenceType"/>
<xs:complexType name="stbType">
  <xs:sequence>
   <xs:element name="titre" type="xs:string"/>
   <xs:element name="version" type="xs:string"/>
   <xs:element name="date" type="xs:string"/>
   <xs:element name="description" type="xs:string"/>
   <xs:element name="client" type="clientType" maxOccurs="1"/>
   <xs:element ref="membre" minOccurs="2" maxOccurs="7"/>
   <xs:element name="fonctionnalite" type="fonctionnaliteType" minOccurs="2" maxOccurs="unbounded"/>
   <xs:element name="commentaire" type="xs:string" minOccurs="0"/>
  </xs:sequence>
</xs:complexType>
<xs:complexType name="clientType">
  <xs:sequence>
   <xs:element name="entite" type="xs:string"/>
   <xs:element name="contact" type="xs:string"/>
   <xs:element name="cp" type="xs:integer"/>
  </xs:sequence>
</xs:complexType>
<xs:complexType name="equipeType">
  <xs:sequence>
   <xs:element name="nom" type="nomType"/>
   <xs:element name="prenom" type="xs:string"/>
  </xs:sequence>
</xs:complexType>
<xs:complexType name="fonctionnaliteType">
  <xs:sequence>
   <xs:element name="description" type="xs:string"/>
   <xs:element ref="exigence" minOccurs="2" maxOccurs="unbounded"/>
  </xs:sequence>
  <xs:attribute name="prioriteatt" type="prioriteType"/>
</xs:complexType>
<xs:complexType name="exigenceType">
  <xs:sequence>
   <xs:element name="identifiant" type="xs:string"/>
   <xs:element name="description" type="xs:string"/>
   <xs:element ref="priorite"/>
  </xs:sequence>
</xs:complexType>
<xs:simpleType name="prioriteType">
  <xs:restriction base="xs:integer">
    <xs:minInclusive value="1"/>
 	 <xs:maxInclusive value="10"/>
  </xs:restriction>
</xs:simpleType>
<xs:complexType name="nomType">
  <xs:sequence>
  	<xs:element name="nom" type="xs:string"/>
  </xs:sequence>
  <xs:attribute name="gender" type="xs:boolean"/>
</xs:complexType>
</xs:schema>

=== abderrahim1992/STB_PROJECT/src/main/resources/stb.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:stb xmlns:p="http://univ.fr/stb" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://univ.fr/stb stb.xsd ">
  <titre>Agora</titre>
  <version>V5-2</version>
  <date>22/02/16</date>
  <description>Jeux en ligne</description>
  <client>
    <entite>Universite</entite>
    <contact>Abderrahim si ziani</contact>
    <cp>76000</cp>
  </client>
  <p:membre>
    <nom gender="true">
      <nom>si ziani</nom>
    </nom>
    <prenom>abderrahim</prenom>
  </p:membre>
  <p:membre>
    <nom gender="false">
      <nom>legoine</nom>
    </nom>
    <prenom>st√©phanie</prenom>
  </p:membre>
  <fonctionnalite prioriteatt="10">
    <description>administration</description>
    <p:exigence>
      <identifiant>01</identifiant>
      <description>Faire le datable</description>
      <p:priorite>10</p:priorite>
    </p:exigence>
    <p:exigence>
      <identifiant>02</identifiant>
      <description>Faire l'interface</description>
      <p:priorite>9</p:priorite>
    </p:exigence>
  </fonctionnalite>
  <fonctionnalite prioriteatt="9">
    <description>Edel, Stein und Reich</description>
    <p:exigence>
      <identifiant>03</identifiant>
      <description>Faire les classes</description>
      <p:priorite>8</p:priorite>
    </p:exigence>
    <p:exigence>
      <identifiant>04</identifiant>
      <description>Faire l'interface</description>
      <p:priorite>7</p:priorite>
    </p:exigence>
  </fonctionnalite>
</p:stb>
